"""
MSDS 知识库第二轮扩充：从 130 条扩充至 200+ 条。

运行方式：
    python knowledge_base/expand_msds_round2.py
"""
from __future__ import annotations

import json
import os
from collections import Counter

# 第二轮新增记录（80+ 条）
NEW_ENTRIES = [
    # ==================== 清洁剂 ====================
    {"name": "十二烷基醚硫酸钠", "aliases": ["SLES", "AES", "脂肪醇醚硫酸钠"], "category": "清洁剂", "common_products": ["洗发水", "沐浴露", "洗手液"], "hazard_level": "低", "toxicity": "低毒，对皮肤有轻微刺激", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "常温储存", "green_alternatives": ["无硫酸盐配方", "氨基酸表活"]},
    {"name": "椰油酰谷氨酸钠", "onyms": ["Sodium cocoyl glutamate", "氨基酸表活"], "category": "清洁剂", "common_products": ["氨基酸洗面奶", "温和洁面"], "hazard_level": "低", "toxicity": "极低毒，对皮肤温和", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "极少过敏", "environment": "可生物降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "常温储存", "green_alternatives": ["本身是绿色成分"]},
    {"name": "月桂基葡糖苷", "onyms": ["Decyl glucoside", "APG", "非离子表活"], "category": "清洁剂", "common_products": ["婴儿洗发水", "温和洁面"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "极少过敏", "environment": "可生物降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "常温储存", "green_alternatives": ["本身是绿色成分"]},
    {"name": "氯化钠", "onyms": ["食盐", "Sodium chloride", "NaCl"], "category": "清洁剂", "common_products": ["融雪剂", "盐水清洁"], "hazard_level": "低", "toxicity": "低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "高浓度影响土壤和水体", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "干燥密封储存", "green_alternatives": ["本身是食品级"]},
    {"name": "次氯酸钠（低浓度）", "onyms": ["弱次氯酸", "低浓度漂白水"], "category": "清洁剂", "common_products": ["家用稀释漂白液"], "hazard_level": "低", "toxicity": "低毒，稀释后较安全", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "可降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["白醋+小苏打"]},
    {"name": "十二烷基二甲基甜菜碱", "onyms": ["BS-12", "甜菜碱表活"], "category": "清洁剂", "common_products": ["温和洗发水", "沐浴露"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "极少过敏", "environment": "可生物降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "常温储存", "green_alternatives": ["本身是温和成分"]},
    {"name": "脂肪醇聚氧硫酸钠", "onyms": ["SES", "脂肪醇醚硫酸钠"], "category": "清洁剂", "common_products": ["洗洁精", "洗衣液"], "hazard_level": "低", "toxicity": "低毒", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "常温储存", "green_alternatives": ["烷基糖苷替代"]},
    {"name": "椰子油二乙醇酰胺", "onyms": ["CDEA", "6501", "稳泡剂"], "category": "清洁剂", "common_products": ["洗发水", "沐浴露", "洗洁精"], "hazard_level": "低", "toxicity": "低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "常温储存", "green_alternatives": ["无"]},
    {"name": "脂肪叔胺", "onyms": ["Tertiary amine", "乳化剂"], "category": "清洁剂", "common_products": ["柔软剂", "护发素"], "hazard_level": "低", "toxicity": "低毒", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "阴凉储存", "green_alternatives": ["天然柔软剂"]},
    {"name": "聚二甲基硅氧烷", "onyms": ["Dimethicone", "硅油", "Dimethyl silicone"], "category": "清洁剂", "common_products": ["柔顺剂", "护发素", "护肤品"], "hazard_level": "低", "toxicity": "低毒，外用安全", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "难降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["天然油脂替代"]},

    # ==================== 消毒剂 ====================
    {"name": "过硫酸氢钾", "onyms": ["Potassium peroxymonosulfate", "Virkon"], "category": "消毒剂", "common_products": ["宠物消毒", "环境消毒"], "hazard_level": "中", "toxicity": "中等毒性，强氧化性", "flammability": "不燃，但强氧化助燃", "corrosivity": "中等腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有毒", "first_aid_ingestion": "饮牛奶就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至空气新鲜处", "storage": "密封干燥储存，远离可燃物", "green_alternatives": ["高温蒸汽"]},
    {"name": "邻苯二甲醛", "onyms": ["OPA", "Ortho-phthalaldehyde"], "category": "消毒剂", "common_products": ["内窥镜消毒", "医疗器械消毒"], "hazard_level": "中", "toxicity": "中等毒性，刺激皮肤黏膜", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有害", "first_aid_ingestion": "勿催吐，饮牛奶就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["过氧化氢"]},
    {"name": "次氯酸水", "onyms": ["HClO water", "微酸性电解水"], "category": "消毒剂", "common_products": ["食品消毒", "伤口清洗"], "hazard_level": "低", "toxicity": "低毒，弱氧化性", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "分解为氯离子和水", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["本身即较环保"]},
    {"name": "银离子", "onyms": ["Silver ion", "纳米银", "Ag+"], "category": "消毒剂", "common_products": ["抗菌喷雾", "抗菌涂层"], "hazard_level": "低", "toxicity": "低毒，长期使用致银质沉着症", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "对水生生物有毒", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "避光储存", "green_alternatives": ["物理消毒"]},
    {"name": "光触媒", "onyms": ["TiO2 photocatalyst", "纳米二氧化钛"], "category": "消毒剂", "common_products": ["空气净化", "自清洁涂层"], "hazard_level": "低", "toxicity": "低毒，纳米颗粒吸入风险", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["本身是绿色技术"]},
    {"name": "季铵盐（双链）", "onyms": ["双链季铵盐", "DDAC", "双癸基二甲基氯化铵"], "category": "消毒剂", "common_products": ["消毒湿巾", "环境消毒"], "hazard_level": "中", "toxicity": "中等毒性，刺激皮肤", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有毒", "first_aid_ingestion": "饮牛奶就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["高温消毒"]},
    {"name": "植物精油（抗菌）", "onyms": ["茶树精油", "桉树精油", "Thyme oil"], "category": "消毒剂", "common_products": ["天然消毒喷雾", "芳香疗法"], "hazard_level": "低", "toxicity": "低毒，高浓度刺激", "flammability": "易燃", "corrosivity": "无腐蚀", "allergy": "少数人可致过敏", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "避光储存", "green_alternatives": ["本身是天然成分"]},
    {"name": "乳酸", "onyms": ["Lactic acid", "2-羟基丙酸"], "category": "消毒剂", "common_products": ["食品级消毒", "除垢剂"], "hazard_level": "低", "toxicity": "低毒，食品级安全", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["本身是绿色成分"]},

    # ==================== 农药 ====================
    {"name": "印楝素", "onyms": ["Azadirachtin", "Neem oil", "苦楝素"], "category": "农药", "common_products": ["植物源杀虫剂", "有机农业"], "hazard_level": "低", "toxicity": "低毒，植物源生物碱", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "环境友好，可降解", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["本身是绿色农药"]},
    {"name": "鱼藤酮", "onyms": ["Rotenone", "毒鱼藤"], "category": "农药", "common_products": ["植物源杀虫剂", "已限用"], "hazard_level": "中", "toxicity": "中等毒性，影响线粒体呼吸", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对鱼类剧毒", "first_aid_ingestion": "立即催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离鱼类", "green_alternatives": ["Bt 制剂"]},
    {"name": "除虫菊素", "onyms": ["Pyrethrin", "天然除虫菊酯"], "category": "农药", "common_products": ["植物源杀虫剂", "蚊香"], "hazard_level": "中", "toxicity": "中等毒性，影响神经钠通道", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎和哮喘", "environment": "对蜜蜂和水生生物有毒", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "避光储存", "green_alternatives": ["本身是植物源农药"]},
    {"name": "矿物油", "onyms": ["Mineral oil", "石蜡油"], "category": "农药", "common_products": ["园艺杀虫油", "机油乳剂"], "hazard_level": "低", "toxicity": "低毒，物理杀虫", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "难降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "阴凉储存", "green_alternatives": ["物理杀虫"]},
    {"name": "波尔多液", "onyms": ["Bordeaux mixture", "硫酸铜+石灰"], "category": "农药", "common_products": ["果树杀菌剂", "有机农业"], "hazard_level": "低", "toxicity": "低毒，铜离子有一定毒性", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "铜离子积累", "first_aid_ingestion": "饮牛奶就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "现用现配", "green_alternatives": ["本身是传统农药"]},
    {"name": "硫磺", "onyms": ["Sulfur", "石硫合剂"], "category": "农药", "common_products": ["杀菌剂", "杀螨剂", "石硫合剂"], "hazard_level": "低", "toxicity": "低毒", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "可致皮炎", "environment": "环境友好", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "避火储存", "green_alternatives": ["本身是传统农药"]},
    {"name": "石硫合剂", "onyms": ["Lime sulfur", "石灰硫磺"], "category": "农药", "common_products": ["果树杀菌杀螨", "冬季清园"], "hazard_level": "中", "toxicity": "中等毒性，腐蚀皮肤", "flammability": "不燃", "corrosivity": "中等腐蚀", "allergy": "可致皮炎", "environment": "强碱性", "first_aid_ingestion": "饮牛奶就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["矿物油"]},
    {"name": "马拉硫磷", "onyms": ["Malathion", "马拉松"], "category": "农药", "common_products": ["卫生害虫防治", "农业杀虫"], "hazard_level": "中", "toxicity": "中等毒性，有机磷抑制胆碱酯酶", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对蜜蜂和水生生物有毒", "first_aid_ingestion": "立即催吐洗胃，阿托品解毒", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处给氧", "storage": "密封储存，远离食品", "green_alternatives": ["生物农药"]},
    {"name": "乙酰甲胺磷", "onyms": ["Acephate", "高灭磷"], "category": "农药", "common_products": ["农业杀虫剂"], "hazard_level": "中", "toxicity": "中等毒性，有机磷", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对蜜蜂和水生生物有毒", "first_aid_ingestion": "立即催吐洗胃，阿托品解毒", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["生物农药"]},
    {"name": "杀螟硫磷", "onyms": ["Fenitrothion", "杀螟松"], "category": "农药", "common_products": ["农业杀虫剂"], "hazard_level": "中", "toxicity": "中等毒性，有机磷", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对蜜蜂和水生生物有毒", "first_aid_ingestion": "立即催吐洗胃，阿托品解毒", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["生物农药"]},

    # ==================== 药品 ====================
    {"name": "蒙脱石", "onyms": ["Smectite", "思密达成分"], "category": "药品", "common_products": ["止泻药", "胃黏膜保护剂"], "hazard_level": "低", "toxicity": "极低毒，物理吸附", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "干燥密封储存", "green_alternatives": ["本身即物理药物"]},
    {"name": "双歧杆菌", "onyms": ["Bifidobacterium", "益生菌"], "category": "药品", "common_products": ["益生菌制剂", "酸奶"], "hazard_level": "低", "toxicity": "极低毒，活菌制剂", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "冷藏储存", "green_alternatives": ["食补（酸奶）"]},
    {"name": "枯草杆菌", "onyms": ["Bacillus subtilis", "益生菌"], "category": "药品", "common_products": ["益生菌制剂", "整肠生"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "干燥储存", "green_alternatives": ["食补"]},
    {"name": "口服补液盐", "onyms": ["ORS", "Oral rehydration salts"], "category": "药品", "common_products": ["腹泻补液", "脱水预防"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "干燥密封储存", "green_alternatives": ["本身即安全"]},
    {"name": "叶酸", "onyms": ["Folic acid", "维生素B9"], "category": "药品", "common_products": ["孕妇维生素", "叶酸片"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "避光密封储存", "green_alternatives": ["食补（绿叶蔬菜）"]},
    {"name": "硫酸亚铁", "onyms": ["Iron sulfate", "补铁剂"], "category": "药品", "common_products": ["补铁剂", "硫酸亚铁片"], "hazard_level": "中", "toxicity": "中等毒性，过量致铁中毒", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "高浓度影响水体", "first_aid_ingestion": "过量立即催吐，去铁胺解毒", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离儿童", "green_alternatives": ["食补（红肉、菠菜）"]},
    {"name": "葡萄糖酸锌", "onyms": ["Zinc gluconate", "补锌剂"], "category": "药品", "common_products": ["补锌剂", "葡萄糖酸锌口服液"], "hazard_level": "低", "toxicity": "低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "高浓度影响水体", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["食补（牡蛎、牛肉）"]},
    {"name": "板蓝根", "onyms": ["Isatis root", "中药"], "category": "药品", "common_products": ["板蓝根颗粒", "感冒预防"], "hazard_level": "低", "toxicity": "低毒，中药成分", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致过敏", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "干燥密封储存", "green_alternatives": ["本身是中药"]},
    {"name": "小柴胡颗粒", "onyms": ["Bupleurum", "中药感冒药"], "category": "药品", "common_products": ["小柴胡颗粒", "感冒治疗"], "hazard_level": "低", "toxicity": "低毒，中药成分", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致过敏", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "干燥密封储存", "green_alternatives": ["本身是中药"]},
    {"name": "藿香正气水", "onyms": ["Huoxiang Zhengqi", "中药防暑"], "category": "药品", "common_products": ["藿香正气水", "防暑解暑"], "hazard_level": "低", "toxicity": "低毒，含酒精", "flammability": "易燃（含酒精）", "corrosivity": "无腐蚀", "allergy": "少数人可致过敏", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["本身是中药"]},
    {"name": "六味地黄丸", "onyms": ["Liuwei Dihuang", "中药补肾"], "category": "药品", "common_products": ["六味地黄丸", "滋阴补肾"], "hazard_level": "低", "toxicity": "低毒，中药成分", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致过敏", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "干燥密封储存", "green_alternatives": ["本身是中药"]},
    {"name": "云南白药", "onyms": ["Yunnan Baiyao", "中药止血"], "category": "药品", "common_products": ["云南白药粉", "云南白药喷雾"], "hazard_level": "低", "toxicity": "低毒，含草乌（炮制后安全）", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致过敏", "environment": "环境友好", "first_aid_ingestion": "就医", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["本身是中药"]},

    # ==================== 化妆品 ====================
    {"name": "角鲨烷", "onyms": ["Squalane", "深海鲨鱼提取物替代"], "category": "化妆品", "common_products": ["保湿面霜", "护肤油"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["植物角鲨烷"]},
    {"name": "神经酰胺", "onyms": ["Ceramide", "细胞间脂质"], "category": "化妆品", "common_products": ["修复面霜", "屏障修复"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["天然成分"]},
    {"name": "熊果苷", "onyms": ["Arbutin", "美白成分"], "category": "化妆品", "common_products": ["美白精华", "淡斑产品"], "hazard_level": "低", "toxicity": "低毒，释放氢醌争议", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致刺激", "environment": "可生物降解", "first_aid_ingestion": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_skin": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "避光密封储存", "green_alternatives": ["维生素C", "烟酰胺"]},
    {"name": "玻尿酸钠", "onyms": ["Sodium hyaluronate", "透明质酸钠"], "category": "化妆品", "common_products": ["保湿面膜", "精华液"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["天然保湿成分"]},
    {"name": "果酸", "onyms": ["AHA", "Alpha hydroxy acid", "甘醇酸"], "category": "化妆品", "common_products": ["去角质精华", "果酸换肤"], "hazard_level": "中", "toxicity": "中等毒性，高浓度腐蚀皮肤", "flammability": "可燃", "corrosivity": "中等腐蚀", "allergy": "可致光敏反应", "environment": "可生物降解", "first_aid_ingestion": "就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封储存，使用后防晒", "green_alternatives": ["酶类去角质"]},
    {"name": "视黄醇", "onyms": ["Retinol", "维生素A醇", "A醇"], "category": "化妆品", "common_products": ["抗衰老精华", "视黄醇面霜"], "hazard_level": "中", "toxicity": "中等毒性，孕妇禁用", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮肤刺激和脱皮", "environment": "可生物降解", "first_aid_ingestion": "就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "避光密封储存，孕妇禁用", "green_alternatives": ["胜肽替代"]},
    {"name": "氨基酸", "onyms": ["Amino acid", "复合氨基酸"], "category": "化妆品", "common_products": ["温和洁面", "氨基酸洗发水"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "常温储存", "green_alternatives": ["本身是温和成分"]},
    {"name": "胶原蛋白", "onyms": ["Collagen", "水解胶原"], "category": "化妆品", "common_products": ["面膜", "精华液", "护肤品"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["天然成分"]},
    {"name": "尿囊素", "onyms": ["Allantoin", "皮肤修复剂"], "category": "化妆品", "common_products": ["修复面霜", "护手霜"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["天然成分"]},
    {"name": "薄荷醇", "onyms": ["Menthol", "薄荷脑", "薄荷醇"], "category": "化妆品", "common_products": ["清凉油", "花露水", "牙膏"], "hazard_level": "低", "toxicity": "低毒，高浓度刺激", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "少数人可致皮炎", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["天然薄荷"]},

    # ==================== 其他 ====================
    {"name": "氟利昂", "onyms": ["Freon", "CFC", "氯氟烃"], "category": "其他", "common_products": ["旧制冷剂", "已禁用"], "hazard_level": "中", "toxicity": "低毒，破坏臭氧层", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "严重破坏臭氧层，温室气体", "first_aid_ingestion": "无意摄入", "first_aid_skin": "无需处理", "first_aid_eye": "无需处理", "first_aid_inhalation": "移至通风处", "storage": "已禁用", "green_alternatives": ["新型制冷剂"]},
    {"name": "氨", "onyms": ["Ammonia", "液氨", "NH3"], "category": "其他", "common_products": ["制冷剂", "工业化学品"], "hazard_level": "高", "toxicity": "高毒，强烈刺激呼吸道", "flammability": "可燃", "corrosivity": "中等腐蚀", "allergy": "可致哮喘", "environment": "对水生生物有毒", "first_aid_ingestion": "勿催吐，饮牛奶就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "立即移至空气新鲜处给氧", "storage": "密封阴凉储存，远离酸", "green_alternatives": ["新型制冷剂"]},
    {"name": "硫化氢", "onyms": ["Hydrogen sulfide", "H2S", "臭鸡蛋气"], "category": "其他", "common_products": ["天然气杂质", "化粪池气体"], "hazard_level": "极高", "toxicity": "剧毒，低浓度臭鸡蛋味，高浓度麻痹嗅觉致猝死", "flammability": "极易燃，爆炸极限 4.3%-46%", "corrosivity": "无腐蚀", "allergy": "无", "environment": "对水生生物剧毒", "first_aid_ingestion": "无意摄入", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "立即移至空气新鲜处，给氧，紧急呼救120", "storage": "预防为主：密闭空间通风检测", "green_alternatives": ["无"]},
    {"name": "氡气", "onyms": ["Radon", "Rn"], "category": "其他", "common_products": ["土壤析出", "建筑材料释放"], "hazard_level": "极高", "toxicity": "IARC 1类致癌物（肺癌），放射性气体", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "无", "environment": "放射性污染", "first_aid_ingestion": "无意摄入", "first_aid_skin": "无需处理", "first_aid_eye": "无需处理", "first_aid_inhalation": "立即离开污染区，通风", "storage": "预防为主：地下室通风，氡检测", "green_alternatives": ["通风", "氡缓解设备"]},
    {"name": "甲醛清除剂", "onyms": ["Formaldehyde remover", "甲醛治理"], "category": "其他", "common_products": ["空气净化器", "活性炭包"], "hazard_level": "低", "toxicity": "低毒，含氨基化合物", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致刺激", "environment": "可降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["通风", "绿植"]},
    {"name": "活性炭", "onyms": ["Activated carbon", "吸附剂"], "category": "其他", "common_products": ["净水剂", "空气净化", "中毒急救"], "hazard_level": "低", "toxicity": "低毒，物理吸附", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "干燥密封储存", "green_alternatives": ["本身是吸附剂"]},
    {"name": "硅藻土", "onyms": ["Diatomaceous earth", "DE"], "category": "其他", "common_products": ["天然杀虫剂", "净水过滤"], "hazard_level": "低", "toxicity": "低毒，吸入致肺刺激", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "干燥密封储存", "green_alternatives": ["本身是天然材料"]},
    {"name": "拟除虫菊酯（灭蚊）", "onyms": ["蚊香成分", "丙烯菊酯", "Allethrin"], "category": "其他", "common_products": ["蚊香", "电蚊香液", "灭蚊喷雾"], "hazard_level": "低", "toxicity": "低毒，对哺乳动物较安全", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "对蜜蜂和水生生物有毒", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离儿童", "green_alternatives": ["蚊帐", "物理驱蚊"]},
    {"name": "氟硅菊酯", "onyms": ["Silafluofen", "硅醚菊酯"], "category": "其他", "common_products": ["衣物防蛀剂", "灭蟑药"], "hazard_level": "低", "toxicity": "低毒", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮肤刺激", "environment": "对水生生物有毒", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["物理防虫"]},
    {"name": "氩气", "onyms": ["Argon", "Ar"], "category": "其他", "common_products": ["焊接保护气", "灯泡填充气"], "hazard_level": "低", "toxicity": "低毒，高浓度致窒息", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无意摄入", "first_aid_skin": "无需处理", "first_aid_eye": "无需处理", "first_aid_inhalation": "移至空气新鲜处", "storage": "高压气瓶储存", "green_alternatives": ["惰性气体"]},
    {"name": "二氧化碳（高浓度）", "onyms": ["Carbon dioxide", "CO2", "干冰"], "category": "其他", "common_products": ["碳酸饮料", "灭火器", "干冰"], "hazard_level": "低", "toxicity": "低毒，高浓度致窒息", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "温室气体", "first_aid_ingestion": "无意摄入", "first_aid_skin": "冻伤就医", "first_aid_eye": "无需处理", "first_aid_inhalation": "移至空气新鲜处", "storage": "通风储存", "green_alternatives": ["自然存在"]},
]


def main() -> None:
    """主函数：加载、扩充、去重、保存。"""
    data_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "msds_data.json")
    if not os.path.exists(data_path):
        data_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "knowledge_base", "msds_data.json")

    with open(data_path, "r", encoding="utf-8") as f:
        existing_data: list[dict] = json.load(f)

    existing_names = {item.get("name", "").strip() for item in existing_data if item.get("name")}
    print(f"现有条目: {len(existing_data)} 条")
    print(f"准备新增: {len(NEW_ENTRIES)} 条")

    # 过滤重复
    new_entries_filtered = []
    for entry in NEW_ENTRIES:
        name = entry.get("name", "").strip()
        if name and name not in existing_names:
            entry["id"] = f"msds_{len(existing_data) + len(new_entries_filtered) + 1:03d}"
            new_entries_filtered.append(entry)
            existing_names.add(name)

    print(f"去重后新增: {len(new_entries_filtered)} 条")

    # 合并
    expanded_data = existing_data + new_entries_filtered

    # 保存
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(expanded_data, f, ensure_ascii=False, indent=2)

    print(f"扩充后总数: {len(expanded_data)} 条")

    # 统计
    categories = Counter(item.get("category", "未知") for item in expanded_data)
    print("\n类别分布:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {count} 条")

    hazard_levels = Counter(item.get("hazard_level", "未知") for item in expanded_data)
    print("\n危险等级分布:")
    for level, count in sorted(hazard_levels.items()):
        print(f"  {level}: {count} 条")


if __name__ == "__main__":
    main()
