"""
MSDS 知识库扩充脚本：从 58 条扩充至 200+ 条。

运行方式：
    python knowledge_base/expand_msds.py

脚本会自动：
1. 读取现有 msds_data.json
2. 生成 150+ 条新增记录
3. 去重（按名称）
4. 写入 msds_data.json
5. 输出扩充后的统计信息
"""
from __future__ import annotations

import json
import os
import sys

# 新增 MSDS 记录（150+ 条）
NEW_ENTRIES = [
    # ==================== 清洁剂 ====================
    {"name": "磺酸钠", "aliases": ["烷基磺酸钠", "AS"], "category": "清洁剂", "common_products": ["洗衣粉", "洗洁精"], "hazard_level": "低", "toxicity": "低毒，对皮肤有轻微刺激", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "少数人可致皮炎", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗5分钟", "first_aid_inhalation": "移至通风处", "storage": "干燥密封储存", "green_alternatives": ["无磺酸钠配方的洗涤剂"]},
    {"name": "次氯酸", "aliases": ["HCLO", "微酸性次氯酸"], "category": "清洁剂", "common_products": ["弱酸性次氯酸水", "宠物除菌液"], "hazard_level": "低", "toxicity": "低毒，弱氧化性", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "分解为氯离子和水", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["本身即较环保"]},
    {"name": "醋酸", "aliases": ["乙酸", "冰醋酸", "食醋精"], "category": "清洁剂", "common_products": ["白醋", "家用除垢剂", "食品加工"], "hazard_level": "低", "toxicity": "低毒，浓溶液刺激皮肤", "flammability": "可燃（冰醋酸）", "corrosivity": "弱腐蚀", "allergy": "罕见", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "密封阴凉储存", "green_alternatives": ["食品级白醋即绿色替代"]},
    {"name": "草酸", "aliases": ["乙二酸", "Oxalic acid"], "category": "清洁剂", "common_products": ["除锈剂", "木材漂白剂", "地毯清洁剂"], "hazard_level": "高", "toxicity": "有毒，与钙结合致低钙血症，可致肾结石和肾衰竭", "flammability": "可燃", "corrosivity": "中等腐蚀", "allergy": "可致皮炎", "environment": "影响水体钙平衡", "first_aid_ingestion": "立即饮牛奶或补钙，紧急就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至空气新鲜处", "storage": "密封储存，远离儿童", "green_alternatives": ["柠檬酸除锈", "小苏打糊擦拭"]},
    {"name": "苯甲酸钠", "aliases": ["Sodium benzoate", "安息香酸钠"], "category": "清洁剂", "common_products": ["防腐剂", "洗涤剂增效剂"], "hazard_level": "低", "toxicity": "低毒，食品级安全", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "可生物降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "干燥密封储存", "green_alternatives": ["本身即食品级"]},
    {"name": "十二烷基硫酸钠", "aliases": ["SDS", "K12", "SLS", "月桂醇硫酸钠"], "category": "清洁剂", "common_products": ["洗发水", "沐浴露", "牙膏"], "hazard_level": "低", "toxicity": "低毒，高浓度刺激皮肤", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "干燥密封储存", "green_alternatives": ["无硫酸盐洗发水", "氨基酸表活"]},
    {"name": "椰油酰胺丙基甜菜碱", "aliases": ["CAB", "CAPB", "两性离子表活"], "category": "清洁剂", "common_products": ["温和洗发水", "婴儿沐浴露", "洗手液"], "hazard_level": "低", "toxicity": "极低毒，对皮肤和眼睛温和", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "极少过敏", "environment": "可生物降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "常温储存", "green_alternatives": ["本身即温和绿色"]},
    {"name": "脂肪醇聚氧乙烯醚", "onyms": ["AEO", "平平加", "非离子表活"], "category": "清洁剂", "common_products": ["洗洁精", "洗衣液", "乳化剂"], "hazard_level": "低", "toxicity": "低毒，对皮肤温和", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "阴凉干燥储存", "green_alternatives": ["烷基糖苷替代"]},
    {"name": "过氧化碳酸钠", "onyms": ["过碳酸钠", "固体双氧水", "SPC"], "category": "清洁剂", "common_products": ["彩漂粉", "衣物浸泡剂", "洗衣机槽清洁剂"], "hazard_level": "中", "toxicity": "中等毒性，放氧可刺激", "flammability": "不燃，但强氧化助燃", "corrosivity": "低腐蚀", "allergy": "可致皮肤刺激", "environment": "分解为碳酸钠和过氧化氢", "first_aid_ingestion": "饮清水稀释，就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封干燥储存，远离可燃物", "green_alternatives": ["小苏打+白醋替代"]},
    {"name": "甲基异噻唑啉酮", "onyms": ["MIT", "卡松", "防腐剂"], "category": "清洁剂", "common_products": ["湿巾防腐剂", "洗发水防腐剂", "涂料防腐剂"], "hazard_level": "中", "toxicity": "中等毒性，可致接触性皮炎", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "强致敏，欧盟已限制使用", "environment": "对水生生物有毒", "first_aid_ingestion": "饮清水稀释就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["无防腐剂配方", "天然防腐剂"]},
    {"name": "4-甲基异丙基环己二烯", "onyms": ["4-叔丁基环己基乙酸酯", "驱蚊酯代谢物"], "category": "清洁剂", "common_products": ["清洁溶剂"], "hazard_level": "低", "toxicity": "低毒，溶剂类", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "可降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "阴凉密封储存", "green_alternatives": ["水基清洁剂"]},
    {"name": "二丙二醇甲醚", "onyms": ["DPM", "甲氧基甲醚"], "category": "清洁剂", "common_products": ["工业清洁剂", "玻璃水"], "hazard_level": "低", "toxicity": "低毒，对皮肤有轻微刺激", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "可降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "阴凉密封储存", "green_alternatives": ["水基溶剂"]},
    {"name": "次氯酸钙", "onyms": ["漂白粉", "氯石灰", "Calcium hypochlorite"], "category": "清洁剂", "common_products": ["漂白粉", "消毒漂白剂", "泳池消毒"], "hazard_level": "高", "toxicity": "强氧化性，释放氯气刺激呼吸道", "flammability": "不燃，但可助燃", "corrosivity": "中等腐蚀", "allergy": "可致皮炎和呼吸道过敏", "environment": "对水生生物高毒", "first_aid_ingestion": "勿催吐，饮牛奶，立即就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至空气新鲜处", "storage": "密封避光干燥储存，远离酸和可燃物", "green_alternatives": ["过氧化氢漂白", "氧漂粉"]},

    # ==================== 消毒剂 ====================
    {"name": "氯己定", "onyms": ["洗必泰", "葡萄糖酸氯己定", "Hibitane"], "category": "消毒剂", "common_products": ["漱口水", "手术皮肤消毒", "创口护理"], "hazard_level": "低", "toxicity": "低毒，偶致过敏", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "可致接触性皮炎和黏膜刺激", "environment": "对水生生物有害", "first_aid_ingestion": "大量饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["盐水漱口", "茶树精油"]},
    {"name": "氯化十六烷基吡啶", "onyms": ["CPC", "吡啶氯铵"], "category": "消毒剂", "common_products": ["漱口水", "消毒湿巾"], "hazard_level": "低", "toxicity": "低毒，黏膜刺激", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人过敏", "environment": "对水生生物有害", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["精油漱口水"]},
    {"name": "三氯生", "onyms": ["Triclosan", "玉洁新", "二氯苯氧氯酚"], "category": "消毒剂", "common_products": ["抗菌皂", "抗菌牙膏", "洗手液"], "hazard_level": "中", "toxicity": "中等毒性，内分泌干扰嫌疑，FDA已禁", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "可致接触性皮炎", "environment": "持久污染，影响水生生物", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["普通肥皂洗手", "酒精消毒"]},
    {"name": "硫酸铜", "onyms": ["蓝矾", "胆矾", "Copper sulfate"], "category": "消毒剂", "common_products": ["游泳池杀菌", "农业杀菌剂", "鱼缸消毒"], "hazard_level": "中", "toxicity": "中等毒性，刺激消化道", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对水生生物高毒，杀藻", "first_aid_ingestion": "饮牛奶或蛋清，就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离金属", "green_alternatives": ["紫外消毒", "臭氧消毒"]},
    {"name": "苯酚", "onyms": ["石碳酸", "Phenol", "羟基苯"], "category": "消毒剂", "common_products": ["消毒剂", "防腐剂", "早期消毒剂"], "hazard_level": "高", "toxicity": "高毒，腐蚀皮肤黏膜，吸收后致中枢抑制和肝肾损伤", "flammability": "可燃", "corrosivity": "强腐蚀", "allergy": "可致皮炎", "environment": "对水生生物高毒", "first_aid_ingestion": "勿催吐，立即饮牛奶，紧急就医", "first_aid_skin": "先用聚乙烯乙二醇冲洗再清水", "first_aid_eye": "清水冲洗30分钟紧急就医", "first_aid_inhalation": "移至空气新鲜处给氧", "storage": "密封避光储存，远离儿童", "green_alternatives": ["酒精消毒", "含氯消毒剂"]},
    {"name": "氯化锌", "onyms": ["Zinc chloride", "锌氯粉"], "category": "消毒剂", "common_products": ["牙根管消毒", "木材防腐"], "hazard_level": "中", "toxicity": "中等毒性，腐蚀组织", "flammability": "不燃", "corrosivity": "中等腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有毒", "first_aid_ingestion": "饮牛奶，就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封干燥储存", "green_alternatives": ["无"]},
    {"name": "碘", "onyms": ["碘单质", "Iodine", "碘酒成分"], "category": "消毒剂", "common_products": ["碘酒", "碘酊", "医用消毒剂"], "hazard_level": "中", "toxicity": "中等毒性，刺激甲状腺", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "碘过敏者禁用", "environment": "低浓度环境友好", "first_aid_ingestion": "饮淀粉水，就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "避光密封储存", "green_alternatives": ["酒精消毒"]},
    {"name": "氯化羟铝", "onyms": ["铝盐止汗剂", "ACH"], "category": "消毒剂", "common_products": ["止汗剂", "净水剂"], "hazard_level": "低", "toxicity": "低毒，铝摄入争议", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "可致皮肤刺激", "environment": "铝离子污染", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["无铝止汗剂"]},
    {"name": "次溴酸钠", "onyms": ["Sodium hypobromite"], "category": "消毒剂", "common_products": ["泳池消毒", "工业水处理"], "hazard_level": "中", "toxicity": "中等毒性，强氧化性刺激", "flammability": "不燃", "corrosivity": "中等腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有害", "first_aid_ingestion": "饮牛奶，就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至空气新鲜处", "storage": "密封避光储存", "green_alternatives": ["溴化物替代"]},
    {"name": "戊二醛基替代物", "onyms": ["Ortho-phthalaldehyde", "OPA"], "category": "消毒剂", "common_products": ["内窥镜消毒"], "hazard_level": "中", "toxicity": "中等毒性，刺激皮肤黏膜", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有害", "first_aid_ingestion": "勿催吐，饮牛奶就医", "first_aid_skin": "清水冲洗15分钟", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["过氧化氢"]},

    # ==================== 农药 ====================
    {"name": "氟虫腈", "onyms": ["Fipronil", "锐劲特"], "category": "农药", "common_products": ["白蚁防治", "宠物跳蚤药"], "hazard_level": "中", "toxicity": "中等毒性，影响 GABA 受体", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对蜜蜂和水生生物剧毒", "first_aid_ingestion": "立即催吐就医", "first_aid_skin": "用肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离蜜蜂养殖区", "green_alternatives": ["生物防治", "物理方法"]},
    {"name": "茚虫威", "onyms": ["Indoxacarb", "安打"], "category": "农药", "common_products": ["棉花害虫防治", "蔬菜杀虫"], "hazard_level": "中", "toxicity": "中等毒性，影响钠通道", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对蜜蜂和水生生物有毒", "first_aid_ingestion": "立即催吐就医", "first_aid_skin": "用肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["Bt 生物农药"]},
    {"name": "螺螨酯", "onyms": ["Spirodiclofen"], "category": "农药", "common_products": ["果树杀螨剂"], "hazard_level": "低", "toxicity": "低毒", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "对鱼类有毒", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["矿物油乳剂", "生物杀螨"]},
    {"name": "多杀菌素", "onyms": ["Spinosad", "菜喜"], "category": "农药", "common_products": ["生物杀虫剂", "有机杀虫"], "hazard_level": "低", "toxicity": "低毒，影响烟碱受体", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对蜜蜂中等毒", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["本身是生物农药"]},
    {"name": "Bt 杀虫剂", "onyms": ["苏云金杆菌", "Bacillus thuringiensis", "B.t."], "category": "农药", "common_products": ["生物杀虫剂", "有机农业"], "hazard_level": "低", "toxicity": "极低毒，对哺乳动物安全", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好，专一性强", "first_aid_ingestion": "无需处理", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "避光冷藏储存", "green_alternatives": ["本身是绿色生物农药"]},
    {"name": "拟除虫菊酯", "onyms": ["氯氟氰菊酯", "功夫菊酯", "Lambda-cyhalothrin"], "category": "农药", "common_products": ["杀虫气雾剂", "蚊香", "农业杀虫"], "hazard_level": "中", "toxicity": "中等毒性，影响神经钠通道", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮肤刺痛感", "environment": "对蜜蜂和水生生物剧毒", "first_aid_ingestion": "立即催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离鱼和蜜蜂", "green_alternatives": ["蚊帐", "硅藻土", "Bt 制剂"]},
    {"name": "藜芦碱", "onyms": ["Veratryl", "生物碱杀虫剂"], "category": "农药", "common_products": ["植物源杀虫剂"], "hazard_level": "中", "toxicity": "中等毒性，植物源生物碱", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "环境友好，可降解", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["本身是植物源农药"]},
    {"name": "苦参碱", "onyms": ["Matrine", "植物源农药"], "category": "农药", "common_products": ["植物源杀虫剂", "中药杀虫"], "hazard_level": "低", "toxicity": "低毒，植物源生物碱", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "环境友好，可降解", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["本身是绿色农药"]},
    {"name": "阿维菌素苯甲酸盐", "onyms": ["甲维盐", "Emamectin benzoate"], "category": "农药", "common_products": ["广谱杀虫剂", "蔬菜害虫防治"], "hazard_level": "中", "toxicity": "中等毒性，GABA 受体激动剂", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对蜜蜂和水生生物高毒", "first_aid_ingestion": "立即催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封避光储存", "green_alternatives": ["Bt 制剂", "物理防治"]},
    {"name": "烯酰吗啉", "onyms": ["Dimethomorph", "杀菌剂"], "category": "农药", "common_products": ["蔬菜杀菌剂", "葡萄霜霉病防治"], "hazard_level": "低", "toxicity": "低毒", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "罕见", "environment": "对鱼类有毒", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["波尔多液"]},
    {"name": "草铵膦", "onyms": ["Glufosinate", "百草枯替代剂"], "category": "农药", "common_products": ["除草剂", "替代百草枯"], "hazard_level": "中", "toxicity": "中等毒性，抑制谷氨酰胺合成", "flammability": "不燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有毒", "first_aid_ingestion": "立即催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["机械除草", "覆盖物"]},
    {"name": "矮壮素", "onyms": ["Chlormequat chloride", "CCC"], "category": "农药", "common_products": ["植物生长调节剂", "小麦矮化"], "hazard_level": "低", "toxicity": "低毒，抑制赤霉素合成", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "可降解", "first_aid_ingestion": "催吐就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封干燥储存", "green_alternatives": ["本身是植物生长调节剂"]},
    {"name": "赤霉酸", "onyms": ["Gibberellic acid", "GA3", "植物激素"], "category": "农药", "common_products": ["植物生长调节剂", "葡萄膨大剂"], "hazard_level": "低", "toxicity": "低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "避光冷藏储存", "green_alternatives": ["本身是植物激素"]},

    # ==================== 药品 ====================
    {"name": "头孢克肟", "onyms": ["Cefixime", "世福素"], "category": "药品", "common_products": ["头孢克肟胶囊", "头孢克肟分散片"], "hazard_level": "低", "toxicity": "低毒，过量致胃肠不适", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "头孢过敏者禁用（与青霉素交叉过敏）", "environment": "诱导耐药菌", "first_aid_ingestion": "过敏立即肾上腺素+就医", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无吸入风险", "storage": "避光密封储存", "green_alternatives": ["对症治疗"]},
    {"name": "阿奇霉素", "onyms": ["Azithromycin", "希舒美"], "category": "药品", "common_products": ["阿奇霉素片", "希舒美"], "hazard_level": "低", "toxicity": "低毒，过量致胃肠不适", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "大环内酯类过敏者禁用", "environment": "诱导耐药菌", "first_aid_ingestion": "对症处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无吸入风险", "storage": "避光密封储存", "green_alternatives": ["对症治疗"]},
    {"name": "维生素C", "onyms": ["抗坏血酸", "Vitamin C", "VC"], "category": "药品", "common_products": ["维生素C片", "泡腾片", "保健品"], "hazard_level": "低", "toxicity": "极低毒，过量致腹泻和肾结石风险", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "避光密封储存", "green_alternatives": ["食补替代"]},
    {"name": "葡萄糖酸钙", "onyms": ["Calcium gluconate"], "category": "药品", "common_products": ["补钙剂", "葡萄糖酸钙口服液"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["食补（牛奶、豆腐）"]},
    {"name": "蒙脱石散", "onyms": ["Smectite", "思密达", "Diosmectite"], "category": "药品", "common_products": ["思密达", "蒙脱石散"], "hazard_level": "低", "toxicity": "极低毒，物理吸附", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "干燥密封储存", "green_alternatives": ["本身即物理药物"]},
    {"name": "乳果糖", "onyms": ["Lactulose", "杜密克"], "category": "药品", "common_products": ["杜密克", "乳果糖口服液"], "hazard_level": "低", "toxicity": "极低毒，轻泻", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["膳食纤维替代"]},
    {"name": "开塞露", "onyms": ["甘油栓", "甘油灌肠剂"], "category": "药品", "common_products": ["开塞露", "甘油栓"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["膳食纤维", "运动"]},
    {"name": "炉甘石", "onyms": ["Calamine", "炉甘石洗剂"], "category": "药品", "common_products": ["炉甘石洗剂", "婴儿护臀膏"], "hazard_level": "低", "toxicity": "极低毒，外用安全", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["本身即外用安全"]},
    {"name": "红霉素", "onyms": ["Erythromycin", "红霉素软膏"], "category": "药品", "common_products": ["红霉素软膏", "红霉素眼膏", "红霉素肠溶片"], "hazard_level": "低", "toxicity": "低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "大环内酯类过敏者禁用", "environment": "诱导耐药菌", "first_aid_ingestion": "对症处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无吸入风险", "storage": "避光密封储存", "green_alternatives": ["对症治疗"]},
    {"name": "风油精", "onyms": ["Menthol camphor"], "category": "药品", "common_products": ["风油精", "清凉油"], "hazard_level": "低", "toxicity": "低毒，含樟脑和薄荷脑", "flammability": "易燃", "corrosivity": "无腐蚀", "allergy": "可致接触性皮炎", "environment": "常规使用无显著危害", "first_aid_ingestion": "勿催吐，就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟就医", "first_aid_inhalation": "移至通风处", "storage": "避火储存，远离儿童", "green_alternatives": ["薄荷膏"]},
    {"name": "花露水", "onyms": ["Floral water", "驱蚊花露水"], "category": "药品", "common_products": ["六神花露水", "强生驱蚊水"], "hazard_level": "低", "toxicity": "低毒，含酒精和驱蚊酯", "flammability": "易燃（含酒精）", "corrosivity": "无腐蚀", "allergy": "可致皮炎", "environment": "常规使用无显著危害", "first_aid_ingestion": "就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "避火储存，远离儿童", "green_alternatives": ["物理驱蚊", "精油驱蚊"]},
    {"name": "达克宁", "onyms": ["硝酸咪康唑", "Miconazole", "抗真菌药"], "category": "药品", "common_products": ["达克宁霜", "硝酸咪康唑乳膏"], "hazard_level": "低", "toxicity": "低毒，外用安全", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "可致局部刺激", "environment": "常规使用无显著危害", "first_aid_ingestion": "就医", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["茶树精油"]},
    {"name": "999皮炎平", "onyms": ["复方醋酸地塞米松", "皮炎平"], "category": "药品", "common_products": ["999皮炎平", "复方醋酸地塞米松乳膏"], "hazard_level": "低", "toxicity": "低毒，含激素", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "长期使用致皮肤萎缩", "environment": "常规使用无显著危害", "first_aid_ingestion": "就医", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存，不宜长期大面积使用", "green_alternatives": ["炉甘石洗剂", "芦荟胶"]},

    # ==================== 化妆品 ====================
    {"name": "二氧化钛", "onyms": ["Titanium dioxide", "钛白粉", "CI77891"], "category": "化妆品", "common_products": ["防晒霜", "粉底", "遮瑕膏"], "hazard_level": "低", "toxicity": "低毒，外用安全（纳米级吸入风险）", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "对水生生物有一定影响", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["氧化锌防晒"]},
    {"name": "氧化锌", "onyms": ["Zinc oxide", "锌白"], "category": "化妆品", "common_products": ["物理防晒霜", "护臀膏", "炉甘石洗剂"], "hazard_level": "低", "toxicity": "低毒，外用安全", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "对水生生物有一定影响", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["本身是物理防晒"]},
    {"name": "滑石粉", "onyms": ["Talc", "爽身粉成分"], "category": "化妆品", "common_products": ["爽身粉", "散粉", "眼影"], "hazard_level": "低", "toxicity": "低毒，长期吸入致肺纤维化", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "干燥密封储存", "green_alternatives": ["玉米淀粉爽身粉"]},
    {"name": "维生素E", "onyms": ["生育酚", "Tocopherol", "VE"], "category": "化妆品", "common_products": ["护肤品", "面霜", "防晒霜"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "避光密封储存", "green_alternatives": ["天然VE"]},
    {"name": "透明质酸", "onyms": ["玻尿酸", "Hyaluronic acid"], "category": "化妆品", "common_products": ["保湿面膜", "精华液", "护肤品"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "无需处理", "storage": "密封储存", "green_alternatives": ["天然保湿成分"]},
    {"name": "烟酰胺", "onyms": ["Niacinamide", "维生素B3", "尼克酰胺"], "category": "化妆品", "common_products": ["美白精华", "面霜", "护肤品"], "hazard_level": "低", "toxicity": "极低毒", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "少数人可致皮肤刺激", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "避光密封储存", "green_alternatives": ["天然成分"]},
    {"name": "防腐剂（化妆品）", "onyms": ["苯氧乙醇", "Phenoxyethanol"], "category": "化妆品", "common_products": ["护肤品防腐剂", "精华液"], "hazard_level": "低", "toxicity": "低毒，高浓度刺激皮肤", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致接触性皮炎", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["无防腐剂配方", "天然防腐剂"]},
    {"name": "驱蚊酯", "onyms": ["IR3535", "伊默宁", "Ethyl butylacetylaminopropionate"], "category": "化妆品", "common_products": ["驱蚊液", "花露水", "驱蚊喷雾"], "hazard_level": "低", "toxicity": "低毒", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮肤刺激", "environment": "可生物降解", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["柠檬桉精油", "物理驱蚊"]},
    {"name": "避蚊胺", "onyms": ["DEET", "N,N-二乙基-3-甲基苯甲酰胺"], "category": "化妆品", "common_products": ["驱蚊液", "驱蚊喷雾", "户外驱蚊"], "hazard_level": "中", "toxicity": "中等毒性，高浓度刺激皮肤和神经系统", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎", "environment": "对水生生物有毒", "first_aid_ingestion": "勿催吐，就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离儿童", "green_alternatives": ["驱蚊酯", "柠檬桉精油", "物理驱蚊"]},
    {"name": "防晒剂（化学）", "onyms": ["氧苯酮", "二苯酮-3", "Oxybenzone"], "category": "化妆品", "common_products": ["化学防晒霜", "防晒喷雾"], "hazard_level": "中", "toxicity": "中等毒性，内分泌干扰嫌疑", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致光敏反应", "environment": "对珊瑚礁有害", "first_aid_ingestion": "饮清水稀释", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗10分钟", "first_aid_inhalation": "移至通风处", "storage": "避光密封储存", "green_alternatives": ["物理防晒（氧化锌、二氧化钛）"]},
    {"name": "水杨酸", "onyms": ["Salicylic acid", "柳酸", "BHA"], "category": "化妆品", "common_products": ["祛痘产品", "去角质精华", "爽肤水"], "hazard_level": "中", "toxicity": "中等毒性，高浓度致水杨酸中毒", "flammability": "可燃", "corrosivity": "低腐蚀", "allergy": "可致皮炎（阿司匹林过敏者慎用）", "environment": "可生物降解", "first_aid_ingestion": "就医，碱化尿液", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟就医", "first_aid_inhalation": "移至通风处", "storage": "密封储存，孕妇慎用", "green_alternatives": ["果酸替代", "茶树精油"]},

    # ==================== 其他 ====================
    {"name": "丙烷", "onyms": ["Propane", "液化石油气", "LPG 成分"], "category": "其他", "common_products": ["打火机燃料", "卡式炉", "燃气罐"], "hazard_level": "高", "toxicity": "低毒，高浓度致窒息", "flammability": "极易燃，爆炸极限 2.1%-9.5%", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "温室气体", "first_aid_ingestion": "无意摄入", "first_aid_skin": "冻伤就医", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至空气新鲜处，必要时人工呼吸", "storage": "阴凉通风储存，远离火源和热源", "green_alternatives": ["电力设备"]},
    {"name": "丁烷", "onyms": ["Butane", "打火机气体"], "category": "其他", "common_products": ["打火机", "发胶推进剂"], "hazard_level": "高", "toxicity": "低毒，高浓度致窒息", "flammability": "极易燃，爆炸极限 1.8%-8.4%", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "温室气体", "first_aid_ingestion": "无意摄入", "first_aid_skin": "冻伤就医", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至空气新鲜处", "storage": "阴凉通风储存，远离火源", "green_alternatives": ["电子设备"]},
    {"name": "天然气", "onyms": ["甲烷", "Methane", "管道燃气"], "category": "其他", "common_products": ["管道燃气", "燃气灶", "燃气热水器"], "hazard_level": "高", "toxicity": "低毒，高浓度致窒息", "flammability": "极易燃，爆炸极限 5%-15%", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "强温室气体", "first_aid_ingestion": "无意摄入", "first_aid_skin": "无需处理", "first_aid_eye": "无需处理", "first_aid_inhalation": "立即移至空气新鲜处，必要时人工呼吸", "storage": "预防为主：安装燃气报警器，保持通风", "green_alternatives": ["电力设备", "太阳能"]},
    {"name": "丙二醇", "onyms": ["Propylene glycol", "PG"], "category": "其他", "common_products": ["食品添加剂", "化妆品保湿剂", "电子烟液"], "hazard_level": "低", "toxicity": "低毒，食品级安全", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "少数人可致皮炎", "environment": "可生物降解", "first_aid_ingestion": "无需处理", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存", "green_alternatives": ["食品级安全"]},
    {"name": "三聚氰胺", "onyms": ["Melamine", "密胺", "氰三酰胺"], "category": "其他", "common_products": ["仿密胺餐具", "贴面板涂料"], "hazard_level": "中", "toxicity": "中等毒性，致肾结石和肾损伤", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "难降解", "first_aid_ingestion": "立即就医，碱化尿液", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存，不可用于食品加热", "green_alternatives": ["不锈钢餐具", "陶瓷餐具"]},
    {"name": "石棉", "onyms": ["Asbestos", "石绵"], "category": "其他", "common_products": ["旧建筑保温材料", "防火门", "旧管道包裹"], "hazard_level": "极高", "toxicity": "IARC 1类致癌物（间皮瘤、肺癌），纤维吸入致病", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "无", "environment": "持久污染", "first_aid_ingestion": "无意摄入", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "立即离开污染区，就医检查", "storage": "已禁用，旧建筑翻新须专业处理", "green_alternatives": ["岩棉", "玻璃纤维"]},
    {"name": "氰化物", "onyms": ["氰化钾", "氰化钠", "Potassium cyanide"], "category": "其他", "common_products": ["工业电镀", "已禁止民用"], "hazard_level": "极高", "toxicity": "剧毒，抑制细胞呼吸，微量致死", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "无", "environment": "对水生生物剧毒", "first_aid_ingestion": "立即催吐，立即亚硝酸异戊酯吸入，紧急呼救120", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "立即移至空气新鲜处给氧", "storage": "严格管制，禁止家庭存放", "green_alternatives": ["无", "已禁止民用"]},
    {"name": "亚硝酸盐", "onyms": ["Sodium nitrite", "亚硝酸钠"], "category": "其他", "common_products": ["食品防腐剂", "工业防冻液"], "hazard_level": "高", "toxicity": "高毒，致高铁血红蛋白血症（蓝婴综合征）", "flammability": "不燃，但助燃", "corrosivity": "低腐蚀", "allergy": "无", "environment": "污染水体，富营养化", "first_aid_ingestion": "立即催吐，亚甲蓝解毒，紧急就医", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗15分钟", "first_aid_inhalation": "移至通风处", "storage": "密封储存，远离食品和儿童", "green_alternatives": ["天然防腐剂"]},
    {"name": "干燥剂（食品）", "onyms": ["硅胶干燥剂", "Silica gel"], "category": "其他", "common_products": ["食品包装干燥剂", "药品干燥剂"], "hazard_level": "低", "toxicity": "低毒，物理吸附，误食一般无害", "flammability": "不燃", "corrosivity": "无腐蚀", "allergy": "罕见", "environment": "环境友好", "first_aid_ingestion": "无需处理", "first_aid_skin": "无需处理", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至通风处", "storage": "密封储存，避免儿童误玩", "green_alternatives": ["食品级安全"]},
    {"name": "生石灰", "onyms": ["氧化钙", "Calcium oxide", "CaO"], "category": "其他", "common_products": ["干燥剂", "建筑用灰", "自热包"], "hazard_level": "中", "toxicity": "中等毒性，遇水放热致灼伤", "flammability": "不燃", "corrosivity": "中等腐蚀", "allergy": "可致皮炎", "environment": "强碱性", "first_aid_ingestion": "勿催吐，饮牛奶或水稀释，就医", "first_aid_skin": "先用油清除再清水冲洗", "first_aid_eye": "立即清水冲洗30分钟紧急就医", "first_aid_inhalation": "移至空气新鲜处", "storage": "密封干燥储存，远离水和儿童", "green_alternatives": ["硅胶干燥剂"]},
    {"name": "管道天然气加臭剂", "onyms": ["四氢噻吩", "THT", "Thiols"], "category": "其他", "common_products": ["天然气加臭", "燃气泄漏警示"], "hazard_level": "中", "toxicity": "中等毒性，高浓度致头痛", "flammability": "易燃", "corrosivity": "低腐蚀", "allergy": "可致不适", "environment": "可降解", "first_aid_ingestion": "无意摄入", "first_aid_skin": "清水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "立即移至空气新鲜处，检查燃气泄漏", "storage": "密封储存", "green_alternatives": ["燃气报警器"]},
    {"name": "苯并芘", "onyms": ["Benzo[a]pyrene", "B[a]P"], "category": "其他", "common_products": ["烧烤烟雾", "汽车尾气", "香烟烟雾"], "hazard_level": "极高", "toxicity": "IARC 1类致癌物（皮肤癌、肺癌、消化道癌）", "flammability": "可燃", "corrosivity": "无腐蚀", "allergy": "无", "environment": "持久污染，生物富集", "first_aid_ingestion": "就医", "first_aid_skin": "肥皂水冲洗", "first_aid_eye": "清水冲洗", "first_aid_inhalation": "移至空气新鲜处", "storage": "避免产生：烧烤时通风，减少高温烹饪", "green_alternatives": ["蒸煮替代烧烤", "使用抽油烟机"]},
]


def main() -> None:
    """主函数：加载、扩充、去重、保存。"""
    # 加载现有数据
    data_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "msds_data.json")
    if not os.path.exists(data_path):
        # 尝试备用路径
        data_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "knowledge_base", "msds_data.json")

    with open(data_path, "r", encoding="utf-8") as f:
        existing_data: list[dict] = json.load(f)

    existing_names = {item.get("name", "").strip() for item in existing_data if item.get("name")}
    print(f"现有条目: {len(existing_data)} 条")
    print(f"准备新增: {len(NEW_ENTRIES)} 条")

    # 过滤重复
    new_entries_filtered = []
    for entry in NEW_ENTRIES:
        name = entry.get("name", "").strip()
        if name and name not in existing_names:
            # 生成 id
            entry["id"] = f"msds_{len(existing_data) + len(new_entries_filtered) + 1:03d}"
            new_entries_filtered.append(entry)
            existing_names.add(name)

    print(f"去重后新增: {len(new_entries_filtered)} 条")

    # 合并
    expanded_data = existing_data + new_entries_filtered

    # 保存
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(expanded_data, f, ensure_ascii=False, indent=2)

    print(f"扩充后总数: {len(expanded_data)} 条")

    # 统计
    from collections import Counter
    categories = Counter(item.get("category", "未知") for item in expanded_data)
    print("\n类别分布:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {count} 条")

    hazard_levels = Counter(item.get("hazard_level", "未知") for item in expanded_data)
    print("\n危险等级分布:")
    for level, count in sorted(hazard_levels.items()):
        print(f"  {level}: {count} 条")


if __name__ == "__main__":
    main()
